/* No provider SDK, analytics, or persisted session content. */
const strings = {
 'pt-BR': {pairTitle:'Seu operador, com você.',pairHelp:'No Mac, abra Avisos e decisões → AgentSmith Pocket e escaneie o QR code. Mantenha o Tailscale ligado nos dois aparelhos.',pair:'Parear este aparelho',pairExpiry:'O QR vale por 5 minutos e pode ser usado uma vez. O acesso dura 12 horas, até você sair ou desligar o Pocket.',now:'Agora',request:'Novo pedido',live:'SEU OPERADOR DIGITAL',title:'O trabalho, de perto.',approval:'SUA APROVAÇÃO',approvalHelp:'Aprova somente esta entrada de mouse ou teclado. Se a tela mudar, uma nova decisão será necessária.',approve:'Aprovar uma vez',reject:'Rejeitar',sessions:'Tarefas',choose:'Selecionar tarefa',empty:'Ainda não há tarefas. Envie seu primeiro pedido.',pause:'Pausar',stop:'Parar',plan:'Plano e histórico',guarded:'Pedir minha aprovação antes de cada ação',start:'Iniciar / retomar este plano',review:'Revise o plano antes de iniciar. A máquina deve estar conectada no Mac.',screen:'Tela da sessão',showFrame:'Mostrar tela',hideFrame:'Ocultar tela',screenHelp:'Imagem atualizada a cada 5 segundos enquanto esta tela estiver aberta. Não é vídeo ao vivo.',guideTitle:'Uma orientação para o Smith',guideHelp:'Pause a tarefa e aguarde. A orientação será usada na próxima retomada, preservando as etapas já concluídas.',message:'Sua orientação',sendGuide:'Salvar orientação',newTask:'PRÓXIMA MISSÃO',requestTitle:'O que vamos fazer?',machine:'Máquina',objective:'Seu objetivo',planHelp:'Smith prepara o roteiro. Você revisa e inicia. Preparar não executa ações no Windows.',prepare:'Preparar roteiro',logout:'Desconectar aparelho',offline:'Sem acesso ao Mac. Verifique o Tailscale e mantenha o AgentSmith aberto.',updated:'Atualizado',sent:'Orientação salva. Retome quando estiver pronto.',preparing:'Preparando roteiro…',ready:'Pronta para revisar',running:'Em execução',verifying:'Verificando',waiting:'Aguardando',paused:'Pausada',blocked:'Precisa de atenção',cancelled:'Parada',completed:'Concluída',expired:'Encerrada',connected:'Conectado',disconnected:'Sem conexão',actions:'ações',steps:'etapas',working:'Aguarde…'},
 en:{pairTitle:'Your operator, with you.',pairHelp:'On your Mac, open Alerts and decisions → AgentSmith Pocket and scan the QR code. Keep Tailscale on both devices.',pair:'Pair this device',pairExpiry:'The QR expires in 5 minutes and works once. Access lasts 12 hours, until you sign out or turn Pocket off.',now:'Now',request:'New request',live:'YOUR DIGITAL OPERATOR',title:'Keep work in sight.',approval:'YOUR APPROVAL',approvalHelp:'Approves only this mouse or keyboard input. If the screen changes, a new decision is needed.',approve:'Approve once',reject:'Reject',sessions:'Tasks',choose:'Select task',empty:'No tasks yet. Send your first request.',pause:'Pause',stop:'Stop',plan:'Plan and history',guarded:'Ask for approval before each action',start:'Start / resume this plan',review:'Review the plan before starting. Connect the machine on the Mac first.',screen:'Session screen',showFrame:'Show screen',hideFrame:'Hide screen',screenHelp:'Image refreshes every 5 seconds while this view is open. This is not live video.',guideTitle:'An instruction for Smith',guideHelp:'Pause the task and wait. The instruction is used on the next resume, preserving completed steps.',message:'Your instruction',sendGuide:'Save instruction',newTask:'NEXT MISSION',requestTitle:'What shall we do?',machine:'Machine',objective:'Your objective',planHelp:'Smith prepares the plan. You review and start it. Planning sends no Windows input.',prepare:'Prepare plan',logout:'Disconnect device',offline:'Cannot reach the Mac. Check Tailscale and keep AgentSmith open.',updated:'Updated',sent:'Instruction saved. Resume when ready.',preparing:'Preparing plan…',ready:'Ready for review',running:'Running',verifying:'Verifying',waiting:'Waiting',paused:'Paused',blocked:'Needs attention',cancelled:'Stopped',completed:'Completed',expired:'Ended',connected:'Connected',disconnected:'Disconnected',actions:'actions',steps:'steps',working:'Please wait…'},
 es:{pairTitle:'Tu operador, contigo.',pairHelp:'En el Mac, abre Avisos y decisiones → AgentSmith Pocket y escanea el QR. Mantén Tailscale activo en ambos dispositivos.',pair:'Vincular este dispositivo',pairExpiry:'El QR vence en 5 minutos y funciona una vez. El acceso dura 12 horas, hasta salir o apagar Pocket.',now:'Ahora',request:'Nuevo pedido',live:'TU OPERADOR DIGITAL',title:'El trabajo, de cerca.',approval:'TU APROBACIÓN',approvalHelp:'Autoriza solo esta entrada de ratón o teclado. Si cambia la pantalla, hará falta otra decisión.',approve:'Aprobar una vez',reject:'Rechazar',sessions:'Tareas',choose:'Seleccionar tarea',empty:'Todavía no hay tareas. Envía tu primer pedido.',pause:'Pausar',stop:'Detener',plan:'Plan e historial',guarded:'Pedir aprobación antes de cada acción',start:'Iniciar / reanudar este plan',review:'Revisa el plan antes de iniciar. Conecta la máquina en el Mac primero.',screen:'Pantalla de la sesión',showFrame:'Mostrar pantalla',hideFrame:'Ocultar pantalla',screenHelp:'La imagen se actualiza cada 5 segundos mientras esta vista está abierta. No es vídeo en directo.',guideTitle:'Una indicación para Smith',guideHelp:'Pausa la tarea y espera. La indicación se usará al reanudar, conservando los pasos completados.',message:'Tu indicación',sendGuide:'Guardar indicación',newTask:'PRÓXIMA MISIÓN',requestTitle:'¿Qué vamos a hacer?',machine:'Máquina',objective:'Tu objetivo',planHelp:'Smith prepara el plan. Tú lo revisas e inicias. Preparar no ejecuta acciones en Windows.',prepare:'Preparar plan',logout:'Desconectar dispositivo',offline:'No se puede acceder al Mac. Revisa Tailscale y mantén AgentSmith abierto.',updated:'Actualizado',sent:'Indicación guardada. Reanuda cuando estés listo.',preparing:'Preparando plan…',ready:'Lista para revisar',running:'En ejecución',verifying:'Verificando',waiting:'Esperando',paused:'Pausada',blocked:'Requiere atención',cancelled:'Detenida',completed:'Completada',expired:'Finalizada',connected:'Conectado',disconnected:'Sin conexión',actions:'acciones',steps:'pasos',working:'Espera…'}
};
const $=id=>document.getElementById(id);
let lang=navigator.language.startsWith('pt')?'pt-BR':navigator.language.startsWith('es')?'es':'en';
let data=null,selected=new URL(location.href).searchParams.get('run')||'',online=false,working=false,showFrame=false,lastFrame=0,tab='now',polling=false;
let pairToken=new URLSearchParams(location.hash.slice(1)).get('pair');
if(pairToken)history.replaceState(null,'',location.pathname+location.search);
const t=key=>strings[lang][key]||key;
function actionText(a){
 const labels={ 'pt-BR':{click:'Clique',double_click:'Clique duplo',right_click:'Clique direito',key:'Teclas',type_text:'Digitar',scroll:'Rolar'},en:{click:'Click',double_click:'Double click',right_click:'Right click',key:'Keys',type_text:'Type',scroll:'Scroll'},es:{click:'Clic',double_click:'Doble clic',right_click:'Clic derecho',key:'Teclas',type_text:'Escribir',scroll:'Desplazar'} };
 const label=labels[lang][a.kind]||a.kind;
 if(a.kind==='type_text')return label+':\n'+a.text;
 if(a.kind==='key')return label+': '+a.keys.join(' + ');
 if('x'in a)return label+': ('+a.x+', '+a.y+')';
 if(a.kind==='scroll')return label+': '+a.direction+' · '+a.amount;
 return label;
}
function translate(){document.documentElement.lang=lang;$('language').value=lang;document.querySelectorAll('[data-t]').forEach(el=>el.textContent=t(el.dataset.t));$('show-frame').textContent=t(showFrame?'hideFrame':'showFrame');if(data)render();}
$('language').onchange=()=>{lang=$('language').value;translate();};
function notice(message){$('notice').textContent=message;}
async function api(path,body){const response=await fetch('/api/'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,cache:'no-store',credentials:'same-origin',signal:AbortSignal.timeout(path==='command'&&body?.kind==='plan'?180000:15000)});const value=await response.json();if(!response.ok){if(response.status===401){data=null;online=false;$('workspace').hidden=true;$('pairing').hidden=false;clearFrame();}throw Error(value.error||String(response.status));}return value;}
function clearFrame(){$('frame').hidden=true;$('frame').removeAttribute('src');lastFrame=0;}
function options(el,items,value){const signature=JSON.stringify(items);if(el.dataset.items!==signature){el.replaceChildren(...items.map(([id,name])=>{const option=document.createElement('option');option.value=id;option.textContent=name;return option;}));el.dataset.items=signature;}if([...el.options].some(o=>o.value===value))el.value=value;}
function current(){return data?.runs.find(r=>r.id===selected);}
function render(){
 $('workspace').hidden=false;$('pairing').hidden=true;
 const session=data.session;const machine=data.machines.find(m=>m.id===session.machineId);
 $('connection').textContent=(machine?.name||'Windows')+' · '+t(session.status||'disconnected');
 options($('machine'),data.machines.map(m=>[m.id,m.name]),$('machine').value||session.machineId);
 if(!data.runs.some(r=>r.id===selected)){selected=data.runs[0]?.id||'';$('guarded').checked=true;}
 options($('run'),data.runs.map(r=>[r.id,r.title+' · '+t(r.status)]),selected);
 $('task-count').textContent=String(data.runs.length);$('empty').hidden=!!data.runs.length;
 const r=current();$('task').hidden=!r;$('guidance').hidden=!r;
 if(r){$('run-title').textContent=r.title;$('progress').textContent=`${t(r.status)} · ${r.steps.filter(s=>s.status==='done').length}/${r.steps.length} ${t('steps')} · ${r.actionCount} ${t('actions')}`+(r.progress?.message?'\n'+r.progress.message:'');
 $('steps').replaceChildren(...r.steps.map(s=>{const li=document.createElement('li');li.textContent=(s.status==='done'?'✓ ':'')+s.title;const small=document.createElement('small');small.textContent=s.success;li.append(small);return li;}));
 $('history').replaceChildren(...r.log.slice(-8).map(text=>{const p=document.createElement('p');p.textContent=text;return p;}));
 const active=['running','verifying','waiting'].includes(r.status),ended=['completed','cancelled','expired'].includes(r.status);
 $('pause').disabled=!online||working||!active;$('stop').disabled=!online||working||ended;$('start').disabled=!online||working||data.busy||ended;$('send-guide').disabled=!online||working||data.busy||ended;$('guarded').disabled=!!data.busy;
 }
 $('prepare').disabled=!online||working||data.planning||!data.machines.length;$('prepare').textContent=t(data.planning?'preparing':'prepare');
 const a=data.approval; $('approval').hidden=!a;
 if(a){$('approval-title').textContent=a.title;$('approval-step').textContent=a.step;$('approval-action').textContent=actionText(a.action);$('approve').disabled=!online||working||Date.now()>=a.expiresAt;$('reject').disabled=$('approve').disabled;}
 $('updated').textContent=t('updated')+' '+new Date().toLocaleTimeString(lang);
}
async function refresh(){if(polling||document.hidden||pairToken)return;polling=true;try{data=await api('state');online=true;render();if(showFrame&&tab==='now'&&Date.now()-lastFrame>=5000){if(data.session.status==='connected'){const snap=await api('frame');if(snap.machineId===data.session.machineId){$('frame').src=snap.frame.dataUrl;$('frame').hidden=false;lastFrame=Date.now();}}else clearFrame();}}catch(e){online=false;clearFrame();if(data){render();notice(t('offline'));}else notice(e.message);}finally{polling=false;}}
async function send(body){if(working)return;working=true;if(data)render();try{const result=await api('command',body);notice('');await refresh();return result;}catch(e){notice(e.message);throw e;}finally{working=false;if(data)render();}}
function action(kind){const r=current();if(!r)return;void send({kind,id:r.id,updated_at:r.updatedAt,...(kind==='start'?{approvals:$('guarded').checked}:{})}).catch(()=>{});}
// Pause/stop intentionally carry no stale revision: they remain available as progress changes.
$('pause').onclick=()=>{const r=current();if(r)void send({kind:'pause',id:r.id}).catch(()=>{});};
$('stop').onclick=()=>{const r=current();if(r)void send({kind:'stop',id:r.id}).catch(()=>{});};
$('start').onclick=()=>action('start');
$('run').onchange=()=>{selected=$('run').value;$('guarded').checked=data.guarded.includes(selected);render();};
$('approve').onclick=()=>{if(data?.approval)void send({kind:'decide',id:data.approval.id,approve:true}).catch(()=>{});};
$('reject').onclick=()=>{if(data?.approval)void send({kind:'decide',id:data.approval.id,approve:false}).catch(()=>{});};
$('guide-form').onsubmit=async e=>{e.preventDefault();const r=current();if(!r)return;try{await send({kind:'guide',id:r.id,updated_at:r.updatedAt,message:$('message').value});$('message').value='';notice(t('sent'));}catch{}};
function selectTab(value){tab=value;$('now').hidden=tab!=='now';$('request').hidden=tab!=='request';document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('selected',b.dataset.tab===tab));if(tab!=='now')clearFrame();}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>selectTab(b.dataset.tab));
$('plan-form').onsubmit=async e=>{e.preventDefault();notice(t('preparing'));try{const result=await send({kind:'plan',machine_id:$('machine').value,instructions:$('instructions').value});if(result){selected=result.run.id;$('instructions').value='';$('guarded').checked=true;selectTab('now');await refresh();}}catch{}};
$('show-frame').onclick=()=>{showFrame=!showFrame;$('show-frame').textContent=t(showFrame?'hideFrame':'showFrame');if(!showFrame)clearFrame();else void refresh();};
$('pair').onclick=async()=>{$('pair').disabled=true;try{await api('pair',{token:pairToken});pairToken=null;notice('');await refresh();}catch(e){notice(e.message);}finally{$('pair').disabled=false;}};
$('logout').onclick=async()=>{try{await api('logout',{});}catch{}data=null;online=false;clearFrame();$('workspace').hidden=true;$('pairing').hidden=false;};
document.addEventListener('visibilitychange',()=>{if(document.hidden)clearFrame();else void refresh();});
translate();$('pairing').hidden=false;$('pair').hidden=!pairToken;
if(!pairToken)void refresh();setInterval(()=>void refresh(),3000);
if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});
