import {useState} from 'react';
import {t,systemText} from './i18n';
import type {Run} from './types';
import './plan-editor.css';
type Draft={title:string;instructions:string;steps:{title:string;success:string}[];updatedAt:number};
export default function PlanEditor({run,mode,close,save,remove}:{run:Run;mode:'edit'|'delete';close:()=>void;save:(draft:Draft)=>Promise<void>;remove:()=>Promise<void>}){
 const [draft,setDraft]=useState<Draft>({title:run.title,instructions:run.instructions,steps:run.steps.map(s=>({title:s.title,success:s.success})),updatedAt:run.updatedAt}),[pending,setPending]=useState(false),[error,setError]=useState('');
 async function submit(){setPending(true);setError('');try{if(mode==='delete')await remove();else await save(draft)}catch(e){setError(String(e));}finally{setPending(false)}}
 function step(index:number,key:'title'|'success',value:string){setDraft(d=>({...d,steps:d.steps.map((s,i)=>i===index?{...s,[key]:value}:s)}))}
 function move(index:number,offset:number){setDraft(d=>{const steps=[...d.steps];[steps[index],steps[index+offset]]=[steps[index+offset],steps[index]];return {...d,steps}})}
 return <div className="modal-backdrop"><section className="modal plan-editor" role="dialog" aria-modal="true" aria-labelledby="plan-editor-title"><h2 id="plan-editor-title">{t(mode==='edit'?'Editar plano':'Excluir plano')}</h2>{mode==='delete'?<><p><strong>{run.title}</strong></p><p className="muted">{t("Atualizado em {0}", {"0":new Date(run.updatedAt).toLocaleString()})} · {run.id.slice(0,8)}</p><p>{t('Somente esta execução e seu registro serão excluídos. Outras execuções com o mesmo título serão mantidas. Isso não desfaz ações já realizadas no Windows.')}</p></>:<p className="muted">{t(run.status==='ready'?'As alterações serão salvas neste plano.':'Será criada uma nova versão pronta para executar. A execução anterior continuará no histórico.')}</p>}
 <form onSubmit={e=>{e.preventDefault();void submit()}}><fieldset disabled={pending}>
 {mode==='edit'&&<><label className="field"><span>{t('Título do plano')}</span><input value={draft.title} required maxLength={200} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label className="field"><span>{t('Instruções do plano')}</span><textarea required maxLength={30000} value={draft.instructions} onChange={e=>setDraft({...draft,instructions:e.target.value})}/></label><p className="muted">{t('Edite também as etapas abaixo para corresponder às instruções. Salvar não consulta a IA nem inicia a execução. As regras OCR e a repetição deverão ser configuradas novamente.')}</p>
 {draft.steps.map((s,i)=><div className="plan-edit-step" key={i}><div className="plan-edit-step-head"><strong>{t('Etapa {0}',{'0':i+1})}</strong><button type="button" className="button secondary" disabled={i===0} aria-label={t('Mover etapa {0} para cima',{'0':i+1})} onClick={()=>move(i,-1)}>↑</button><button type="button" className="button secondary" disabled={i===draft.steps.length-1} aria-label={t('Mover etapa {0} para baixo',{'0':i+1})} onClick={()=>move(i,1)}>↓</button><button type="button" className="button secondary" disabled={draft.steps.length===1} aria-label={t('Remover etapa {0}',{'0':i+1})} onClick={()=>setDraft({...draft,steps:draft.steps.filter((_,n)=>n!==i)})}>{t('Remover etapa')}</button></div><label className="field"><span>{t('Ação')}</span><textarea required maxLength={4000} value={s.title} onChange={e=>step(i,'title',e.target.value)}/></label><label className="field"><span>{t('Resultado esperado')}</span><textarea required maxLength={4000} value={s.success} onChange={e=>step(i,'success',e.target.value)}/></label></div>)}
 <button type="button" className="button secondary" disabled={draft.steps.length>=30} onClick={()=>setDraft({...draft,steps:[...draft.steps,{title:'',success:''}]})}>{t('Adicionar etapa')}</button></>}
 {error&&<div className="alert" role="alert">{systemText(error)}</div>}<div className="modal-actions"><button type="button" className="button secondary" onClick={close}>{t('Cancelar')}</button><button className={'button '+(mode==='delete'?'stop-button':'primary')}>{pending?t(mode==='delete'?'Excluindo…':'Salvando…'):t(mode==='delete'?'Excluir definitivamente':run.status==='ready'?'Salvar plano':'Salvar nova versão')}</button></div>
 </fieldset></form></section></div>
}
