import {useEffect,useState} from 'react';
import {Check,Copy,Loader2,Smartphone,ShieldCheck} from 'lucide-react';
import {t,systemText} from './i18n';
import type {SimplexStatus} from './types';
type Props={call:<T>(name:string,args?:Record<string,unknown>)=>Promise<T>};
export default function SimplexChannel({call}:Props){
 const [status,setStatus]=useState<SimplexStatus|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[server,setServer]=useState(''),[step,setStep]=useState(1),[sent,setSent]=useState(false),[serverReady,setServerReady]=useState(false),[now,setNow]=useState(Date.now());
 useEffect(()=>{let mounted=true,running=false;async function refresh(){if(running)return;running=true;try{const s=await call<SimplexStatus>('simplex_status');if(mounted)setStatus(s);}catch{}finally{running=false;}}void refresh();const timer=setInterval(()=>{setNow(Date.now());void refresh();},2500);return()=>{mounted=false;clearInterval(timer);};},[]);
 async function run(fn:()=>Promise<unknown>){setBusy(true);setError('');setSent(false);try{await fn();setStatus(await call<SimplexStatus>('simplex_status'));}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function copy(value:string){try{await navigator.clipboard.writeText(value);}catch{setError(t('Não foi possível copiar.'));}}
 const active=!!status?.active,local=!!status?.local,paired=(status?.contacts??0)>0,pairing=active&&(status?.pairingUntil??0)>now;
 const serverQr=status?.host.serverQr;
 return <section className="panel simplex-channel"><div className="panel-head"><div><span className="tiny-label">SIMPLEX</span><h3>{t('Seu Mac conecta os celulares')}</h3></div><ShieldCheck size={22}/></div>
 <p>{t('O AgentSmith prepara um servidor privado neste Mac. Conecte seu iPhone ou Android pelos QR codes para receber avisos e responder aos pedidos de decisão.')}</p>
 <p className="info-strip">{t('Mantenha o Mac acordado e o Tailscale conectado nos aparelhos. No celular, instale o SimpleX Chat. O pareamento cria um contato; não copia sua conta ou histórico do SimpleX.')}</p>
 <div className="button-row">{!active?<button className="button primary" disabled={busy} onClick={()=>void run(async()=>{setStep(1);setServerReady(false);await call('simplex_start_local');})}>{busy?<Loader2 size={16} className="spin"/>:<ShieldCheck size={16}/>} {busy?t('Preparando…'):t('Preparar e ativar neste Mac')}</button>:<><span className="simplex-state"><Check size={16}/>{local?t('Servidor neste Mac'):t('Servidor externo')} · {paired?t('{count} contato(s) pareado(s)',{count:String(status?.contacts??0)}):t('Aguardando celular')}</span><button className="button secondary" disabled={busy} onClick={()=>void run(async()=>{await call('simplex_stop');setStep(1);setServerReady(false);})}>{t('Desligar SimpleX')}</button></>}</div>
 {busy&&<p role="status" aria-live="polite">{systemText(status?.host.message||t('Preparando…'))}</p>}
 {!active&&!busy&&status?.host.phase&&<button className="button secondary" onClick={()=>void run(()=>call('simplex_stop'))}>{t('Desligar SimpleX')}</button>}
 {(error||status?.host.phase==='error'||!active&&status?.message)&&<p role="alert" className="login-error">{systemText(error||status?.host.message||status?.message||'')}</p>}
 {active&&<div className="simplex-setup"><div className="simplex-steps" aria-label={t('Conectar celular')}>
 {local&&<button className={'button '+(step===1?'primary':'secondary')} onClick={()=>setStep(1)}>1 · {t('Servidor no celular')}</button>}
 <button className={'button '+(step===2?'primary':'secondary')} disabled={local&&!serverReady&&!paired} onClick={()=>setStep(2)}>{local?'2 · ':''}{t('Adicionar AgentSmith')}</button><button className={'button '+(step===3?'primary':'secondary')} onClick={()=>setStep(3)}>{local?'3 · ':''}{t('Confirmar')}</button></div>
 {local&&step===1&&serverQr&&<div className="pocket-pair"><img className="simplex-qr" width="280" height="280" src={'data:image/svg+xml;base64,'+btoa(serverQr)} alt={t('QR do servidor SimpleX')}/><div><span className="tiny-label">{t('QR DE SERVIDOR')}</span><h3>{t('Adicione este servidor no SimpleX')}</h3><p className="info-strip">{t('Este QR deve ser lido na lista de servidores. O leitor de New chat aceita apenas o QR de contato da etapa 2.')}</p><ol><li>{t('No iPhone: Settings → Network & servers → Your servers → Add server → Scan server QR code. No Android, abra a lista de servidores nas configurações de rede e escolha adicionar por QR.')}</li><li>{t('Adicione um servidor pelo leitor de QR e escaneie este código. Teste e salve.')}</li><li>{t('Use este servidor para novas conexões e desative os servidores de mensagens padrão se quiser manter os dois sentidos neste Mac.')}</li></ol><p className="hint">{t('Se aparecer Private routing error, confira se este servidor foi salvo. Em Network & servers → Advanced network settings → Private routing, use a opção para servidores desconhecidos em vez de Always. Assim, o Mac cadastrado recebe a conexão diretamente pelo Tailscale.')}</p><div className="button-row"><button className="button secondary" onClick={()=>void copy(status.host.serverAddress)}><Copy size={14}/>{t('Copiar endereço do servidor')}</button><button className="button primary" onClick={()=>{setServerReady(true);setStep(2);}}>{t('Testei e salvei o servidor no celular')}</button></div></div></div>}
 {(step===2||!local&&step===1)&&<><span className="tiny-label">{t('QR DE CONTATO · NEW CHAT')}</span><h3>{t('Conecte o celular ao AgentSmith')}</h3><p>{t('No SimpleX do celular, escolha adicionar contato e escanear QR. A pessoa que se conectar poderá receber avisos e responder às decisões do AgentSmith.')}</p>
 {local&&<p className="info-strip">{t('Private routing error: o celular tentou usar um intermediário público. Volte à etapa 1, salve o servidor e confira Private routing. Depois gere o QR de contato e tente novamente com o Tailscale conectado.')}</p>}
 {pairing&&status?.qr?<div className="pocket-pair"><img className="simplex-qr" width="300" height="300" src={'data:image/svg+xml;base64,'+btoa(status.qr)} alt={t('QR para adicionar AgentSmith')}/><div><strong>{t('QR válido por 5 minutos')}</strong><p>{t('Envie uma mensagem ao AgentSmith para confirmar a conexão. Os contatos conectados permanecem salvos após fechar o app.')}</p><button className="button secondary" onClick={()=>void copy(status.address)}><Copy size={14}/>{t('Copiar link de pareamento')}</button></div></div>:<button className="button primary" disabled={busy} onClick={()=>void run(()=>call('simplex_pair'))}><Smartphone size={16}/>{t('Mostrar QR para conectar celular')}</button>}
 {paired&&<p className="simplex-state"><Check size={16}/>{t('{count} contato(s) pareado(s)',{count:String(status?.contacts??0)})}<button className="button secondary" onClick={()=>setStep(3)}>{t('Confirmar')}</button></p>}</>}
 {step===3&&<><h3>{paired?t('Celular conectado'):t('Aguardando celular')}</h3><p>{t('Envie uma mensagem ao AgentSmith para confirmar a conexão. Os contatos conectados permanecem salvos após fechar o app.')}</p><button className="button primary" disabled={busy||!paired} onClick={()=>void run(async()=>{await call('simplex_test_notice');setSent(true);})}>{sent?t('Aviso enviado'):t('Enviar aviso de teste')}</button></>}
 </div>}
 <details className="simplex-advanced"><summary>{t('Avançado: usar um servidor externo')}</summary><p>{t('Use esta opção se você já mantém um servidor SimpleX. O endereço é salvo no Chaves do macOS.')}</p><label className="field"><span>{t('Endereço do servidor')}</span><input type="password" value={server} onChange={e=>setServer(e.target.value)} placeholder="smp://…@servidor:5223" autoComplete="off" spellCheck={false}/></label><div className="button-row"><button className="button secondary" disabled={busy||!server.trim()} onClick={()=>void run(async()=>{await call('simplex_save_server',{server});setServer('');setStep(2);})}>{t('Salvar e ativar servidor externo')}</button><button className="button secondary" disabled={busy} onClick={()=>void run(async()=>{await call('simplex_start');setStep(2);})}>{t('Usar servidor externo salvo')}</button></div></details>
 </section>
}
