import {useEffect,useRef,useState} from 'react';
import {t,systemText} from './i18n';
import {imagePoint} from './geometry';
import type {Region,Run,Snapshot,TextCheck} from './types';
import './ocr.css';
type Reading={elapsedMs:number;lines:({text:string;confidence:number}&Region)[]};
type Row={model:string;mode:string;elapsedMs:number;text:string;correct:boolean;error?:string};
type Call=<T>(name:string,args?:Record<string,unknown>)=>Promise<T>;
export default function TextCheckForm({run,index,call,close,saved}:{run:Run;index:number;call:Call;close:()=>void;saved:()=>Promise<void>}){
 const initial=run.steps[index].textCheck;
 const [frame,setFrame]=useState<Snapshot|null>(null),[reading,setReading]=useState<Reading|null>(null),[region,setRegion]=useState<Region|undefined>(initial?.region),[expected,setExpected]=useState(initial?.expected??''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[comparing,setComparing]=useState(false),[models,setModels]=useState<{id:string;name:string}[]>([]),[model,setModel]=useState(''),[rows,setRows]=useState<Row[]>([]);
 const anchor=useRef<{x:number;y:number}|null>(null), mounted=useRef(true);
 useEffect(()=>{mounted.current=true;void capture();void call<{models:{id:string;name:string;installed:boolean}[]}>('local_engine_status').then(s=>{if(!mounted.current)return;const m=s.models.filter(m=>m.installed);setModels(m);setModel(m[0]?.id??'')}).catch(e=>setError(String(e)));return()=>{mounted.current=false;void call('cancel_reading_test').catch(()=>{})}},[]);
 async function capture(){setBusy(true);setError('');try{const [f,r]=await call<[Snapshot,Reading]>('read_screen_text');if(mounted.current){setFrame(f);setReading(r);setRows([]);if(initial&&(f.width!==initial.screenWidth||f.height!==initial.screenHeight))setRegion(undefined);}}catch(e){if(mounted.current)setError(String(e));}finally{if(mounted.current)setBusy(false);}}
 const check:TextCheck|undefined=region&&frame?{expected,region,screenWidth:frame.width,screenHeight:frame.height}:undefined;
 const valid=!!check&&expected.trim().length>0&&region!.width>=8&&region!.height>=8;
 async function save(clear=false){if(!clear&&!valid)return;setBusy(true);setError('');try{await call('set_step_text_check',{id:run.id,index,check:clear?null:check});await saved();}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function compare(){if(!valid||!model)return;setComparing(true);setRows([]);setError('');try{const result=await call<Row[]>('compare_reading',{frame,check,modelId:model});if(mounted.current)setRows(result);}catch(e){if(mounted.current)setError(String(e));}finally{if(mounted.current)setComparing(false);}}
 function point(e:React.PointerEvent<HTMLDivElement>){return frame?imagePoint(e.clientX,e.clientY,e.currentTarget.getBoundingClientRect(),frame.width,frame.height):null;}
 return <div className="modal-backdrop"><section className="modal ocr-modal" role="dialog" aria-modal="true" aria-labelledby="ocr-title"><h2 id="ocr-title">{t('Texto esperado (OCR)')}</h2><p>{run.steps[index].title}</p><p className="muted">{t('Selecione somente o campo ou visor. Esta regra confirma a etapa quando o texto exato aparece nessa região, sem consultar o LLM. Use apenas quando isso comprovar o resultado completo da etapa.')}</p>
 {frame&&<div className="ocr-image" style={{aspectRatio:`${frame.width}/${frame.height}`}} onPointerDown={e=>{if(busy||comparing)return;const p=point(e);if(p){anchor.current=p;e.currentTarget.setPointerCapture(e.pointerId);setRegion({x:p.x,y:p.y,width:0,height:0});}}} onPointerMove={e=>{const a=anchor.current,p=point(e);if(a&&p)setRegion({x:Math.min(a.x,p.x),y:Math.min(a.y,p.y),width:Math.abs(a.x-p.x)+1,height:Math.abs(a.y-p.y)+1});}} onPointerUp={()=>{anchor.current=null;}} onPointerCancel={()=>{anchor.current=null;}}><img draggable={false} src={frame.dataUrl} alt={t('Selecione a região na captura do Windows')}/>{region&&<div className="ocr-selection" style={{left:`${region.x/frame.width*100}%`,top:`${region.y/frame.height*100}%`,width:`${region.width/frame.width*100}%`,height:`${region.height/frame.height*100}%`}}/>}</div>}
 <p className="muted">{t('Imagem congelada apenas na memória. Arraste para selecionar ou clique em um texto detectado abaixo.')}</p>
 <div className="ocr-detections">{reading?.lines.filter(l=>l.confidence>=.8).map((l,i)=><button type="button" disabled={busy||comparing} key={i} title={`${Math.round(l.confidence*100)}% · ${l.x},${l.y}`} onClick={()=>{if(!frame)return;const x=Math.max(0,l.x-8),y=Math.max(0,l.y-8);setRegion({x,y,width:Math.min(frame.width-x,l.width+16),height:Math.min(frame.height-y,l.height+16)});setExpected(l.text)}}>{l.text}</button>)}</div>
 <label className="field"><span>{t('Texto exato esperado')}</span><input maxLength={160} value={expected} disabled={busy||comparing} onChange={e=>setExpected(e.target.value)} placeholder="16.666.666"/></label>
 <div className="ocr-coordinates">{(['x','y','width','height'] as const).map((key,i)=><label key={key}>{[t('Posição X'),t('Posição Y'),t('Largura'),t('Altura')][i]}<input type="number" min={i<2?0:8} disabled={!frame||busy||comparing} value={region?.[key]??0} onChange={e=>setRegion({...region??{x:0,y:0,width:8,height:8},[key]:Number(e.target.value)})}/></label>)}</div>
 <p className="muted">{t('Confiança mínima de 98%. Se a resolução mudar, ajuste a região. Em loops, o texto precisa mudar antes de reaparecer em cada ciclo. O OCR não prova que uma instalação ou gravação terminou, a menos que a mensagem escolhida comprove isso.')}</p>
 <div className="ocr-benchmark"><strong>{t('Comparar leitura na mesma imagem')}</strong><p className="muted">{t('Informe o texto que está visível agora. Compara acerto e tempo de leitura, não a execução completa de tarefas. A primeira consulta pode incluir o carregamento do modelo. O roteamento permanece igual.')}</p><select aria-label={t('Modelo para comparação')} value={model} disabled={busy||comparing||!models.length} onChange={e=>setModel(e.target.value)}>{models.length?models.map(m=><option key={m.id} value={m.id}>{t(m.name)}</option>):<option>{t('Baixe um modelo em Provedores e modelos')}</option>}</select><button className="button secondary" disabled={!valid||!model||busy||comparing} onClick={()=>void compare()}>{comparing?t('Comparando…'):t('Comparar leitura')}</button>{comparing&&<button className="button secondary" onClick={()=>void call('cancel_reading_test')}>{t('Cancelar comparação')}</button>}
 {rows.length>0&&<table><thead><tr><th>{t('Modelo')}</th><th>{t('Modo')}</th><th>{t('Tempo')}</th><th>{t('Leitura')}</th><th>{t('Acerto')}</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td>{r.model}</td><td>{r.mode.replace('crop',t('Recorte')).replace('full',t('Tela inteira'))}</td><td>{(r.elapsedMs/1000).toFixed(2)} s</td><td>{r.error?systemText(r.error):r.text}</td><td>{r.correct?t('Sim'):t('Não')}</td></tr>)}</tbody></table>}</div>
 {error&&<div className="alert" role="alert">{systemText(error)}</div>}<div className="modal-actions"><button className="button secondary" disabled={busy||comparing} onClick={()=>void capture()}>{t('Atualizar captura')}</button>{initial&&<button className="button secondary" disabled={busy||comparing} onClick={()=>void save(true)}>{t('Remover regra OCR')}</button>}<button className="button secondary" disabled={busy||comparing} onClick={close}>{t('Fechar')}</button><button className="button primary" disabled={!valid||busy||comparing} onClick={()=>void save()}>{t('Salvar regra OCR')}</button></div>
 </section></div>
}
